import {SdTurboRuntime} from './runtime/sd-turbo';import {LongLiveRuntime} from './runtime/longlive';import {MemFlowRuntime} from './runtime/memflow';import type {LoadProgress} from './runtime/common';
let runtime:any,controller=new AbortController();const post=(x:any,transfer?:Transferable[])=>self.postMessage(x,{transfer:transfer??[]});
// Aggregate per-file byte progress into a single percentage + file list for the UI.
function reporter():LoadProgress{
 const files=new Map<string,{loaded:number;total:number;cached:boolean}>();
 const flush=(message?:string)=>{const list=[...files.entries()].map(([name,f])=>({name,...f}));const loaded=list.reduce((s,f)=>s+f.loaded,0),total=list.reduce((s,f)=>s+(f.total||f.loaded),0);const percent=total?Math.min(100,Math.round(loaded/total*100)):0;post({type:'progress',percent,loaded,total,cached:list.length>0&&list.every(f=>f.cached),files:list,message});};
 return {status:(message)=>flush(message),file:(name,loaded,total,cached)=>{files.set(name,{loaded,total,cached});flush();}};
}
self.onmessage=async(e)=>{try{const m=e.data;if(m.type==='stop'){controller.abort();return}if(m.type==='load'){const p=reporter();p.status('Reading manifest…');runtime=m.mode==='sd'?new SdTurboRuntime():m.mode==='memflow'?new MemFlowRuntime():new LongLiveRuntime();await runtime.load(m.manifestUrl,p);post({type:'progress',percent:100,done:true,message:'Model ready'});return}if(m.type==='run'){if(!runtime)throw new Error('Load the model first');controller=new AbortController();post({type:'status',message:'Generating…'});await runtime.run(m.prompt,m.steps,m.seed,(f:any)=>{post({type:'frame',...f},[f.rgba.buffer])},controller.signal);post({type:'status',message:'Complete'})}}catch(err){post({type:'status',error:true,message:err instanceof Error?`${err.name}: ${err.message}`:String(err)})}};
